version: 2.1
orbs:
  android: circleci/android@2.2.0
  gradle: circleci/gradle@3.0.0

jobs:
  kotlin-build:
    machine:
      image: android:2023.04.1
    steps:
      - checkout

      - gradle/collect_test_results
      - store_artifacts:
          path: report.json
  kotlin-test:
    docker:  
      - image: cimg/android:2023.04
    steps:
      - checkout
      - android/create-avd:
          avd-name: 'Kotlin AVD'
          install: false
          system-image: system-images;android-UpsideDownCake;default;x86
      - android/start-emulator-and-run-tests:
          avd-name: 'Kotlin AVD'
      

workflows:
  test-and-build-kotlin:
    jobs:
      - gradle/test
      - kotlin-test
      - kotlin-build
          requires:
            - kotlin-test
      - android/run-ui-tests
      - gradle/run:
          requires:
            - gradle/test
            - android/run-ui-tests
     